webtalk_init -webtalk_dir C:/Users/Agnese/Desktop/HOMELABS/1-Intel8051Microcontroller/workspaces/euclid/i8051VHDL/i8051Keil/i8051Keil.sim/sim_1/behav/xsim/xsim.dir/I8051_TSB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 22 12:58:12 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "57c5070f-df6f-471f-95ae-1c24d6b04478" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e600ff744b404b88aa0cabff2730d805" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7784_KB" -context "xsim\\usage"
webtalk_transmit -clientid 650866387 -regid "" -xml C:/Users/Agnese/Desktop/HOMELABS/1-Intel8051Microcontroller/workspaces/euclid/i8051VHDL/i8051Keil/i8051Keil.sim/sim_1/behav/xsim/xsim.dir/I8051_TSB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Agnese/Desktop/HOMELABS/1-Intel8051Microcontroller/workspaces/euclid/i8051VHDL/i8051Keil/i8051Keil.sim/sim_1/behav/xsim/xsim.dir/I8051_TSB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Agnese/Desktop/HOMELABS/1-Intel8051Microcontroller/workspaces/euclid/i8051VHDL/i8051Keil/i8051Keil.sim/sim_1/behav/xsim/xsim.dir/I8051_TSB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
